[build]
  publish = "."
  command = "echo 'Zero-cost deployment ready'"

[[redirects]]
  from = "/"
  to = "/landing-zero-cost.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"